// Generates random message as a reply to the Magic Eight Ball

// 1. Random Number Generator function
const random = (max) => {
    console.log('Magic Eighball\'s answer to your quesiton is: ')
    return Math.floor(Math.random() * max)
}

// 2.  Identify possible respones
const responses = [
    'It is certain.',
    'It is decidedly so.',
    'Without a doubt.',
    'Yes, definitely.',
    'You may rely on it.',
    'As I see it, yes',
    'Most likely.',
    'Outlook good.',
    'Reply hazy, try again.',
    'Ask again later',
    'Better not tell you now.',
    'Concentrate and ask again',
    'Do not count on it.',
    'My reply is no.',
    'Outlook is not so good.',
    'Very doubful'
]

// 3. Random reponses generated by a function selecting items in the array from #2
const randMsgGen = () => {
    let len = responses.length;
    return responses[random(len)];
}

// 4.  Console.log the random responses
console.log(randMsgGen())